# Generated by Django 5.0.14 on 2025-10-21 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama Masjid')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Kota/Kab')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='Provinsi')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Berdiri')),
                ('land_status', models.CharField(blank=True, max_length=120, verbose_name='Status Tanah')),
                ('deed_number', models.CharField(blank=True, max_length=120, verbose_name='No. Akta/Surat Wakaf')),
                ('npwp', models.CharField(blank=True, max_length=32, verbose_name='NPWP')),
                ('bank_name', models.CharField(blank=True, max_length=80, verbose_name='Bank Utama')),
                ('bank_account', models.CharField(blank=True, max_length=80, verbose_name='No. Rekening')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL Logo')),
                ('about', models.TextField(blank=True, verbose_name='Tentang Masjid')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('KET', 'Ketua DKM'), ('BEN', 'Bendahara'), ('SEK', 'Sekretaris'), ('IMAM', 'Imam'), ('LAIN', 'Lainnya')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='core.mosque')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='core.mosque')),
            ],
        ),
        migrations.CreateModel(
            name='DonationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bank', models.CharField(blank=True, max_length=80)),
                ('account', models.CharField(blank=True, max_length=80)),
                ('qris_image', models.ImageField(blank=True, null=True, upload_to='qris/')),
                ('is_active', models.BooleanField(default=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.mosque')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AKTA', 'Akta/Surat Wakaf'), ('SK', 'SK Pengurus/Organisasi'), ('NPWP', 'NPWP'), ('REK', 'Buku Rek Bank'), ('LAIN', 'Dokumen Lain')], max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='docs/')),
                ('is_public', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.mosque')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.mosque')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Laporan Keuangan Masjid', max_length=150)),
                ('file', models.FileField(upload_to='reports/')),
                ('period', models.CharField(blank=True, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.mosque')),
            ],
        ),
    ]
