# Generated by Django 5.0.14 on 2025-10-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nomor Kontak (WA/Telp)'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Resmi'),
        ),
    ]
