# Generated by Django 5.0.14 on 2025-11-11 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mosque_contact_phone_mosque_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ZAKAT', 'Zakat'), ('INFAQ', 'Infaq'), ('SEDEKAH', 'Sedekah')], max_length=10, verbose_name='Jenis Donasi')),
                ('donor_name', models.CharField(blank=True, max_length=120, verbose_name='Nama Donatur')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Nominal (opsional)')),
                ('note', models.TextField(blank=True, verbose_name='Catatan (opsional)')),
                ('proof', models.FileField(upload_to='proofs/%Y/%m/', verbose_name='Bukti Transfer (jpg/png/pdf)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_proofs', to='core.mosque')),
            ],
        ),
    ]
