# Generated by Django 5.0.14 on 2025-11-11 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donationproof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationproof',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='donationproof',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='donationproof',
            name='kind',
        ),
        migrations.AddField(
            model_name='donationproof',
            name='donation_type',
            field=models.CharField(choices=[('ZKT', 'Zakat'), ('INF', 'Infak'), ('SDK', 'Sedekah')], default='Zakat', max_length=3, verbose_name='Jenis Donasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationproof',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Tampilkan ke publik?'),
        ),
        migrations.AddField(
            model_name='donationproof',
            name='paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Transfer'),
        ),
        migrations.AddField(
            model_name='donationproof',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='No. HP/WA'),
        ),
        migrations.AddField(
            model_name='donationproof',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationproof',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Jumlah (Rp)'),
        ),
        migrations.AlterField(
            model_name='donationproof',
            name='donor_name',
            field=models.CharField(max_length=120, verbose_name='Nama Donatur'),
        ),
        migrations.AlterField(
            model_name='donationproof',
            name='note',
            field=models.TextField(blank=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='donationproof',
            name='proof',
            field=models.FileField(upload_to='proof/', verbose_name='Bukti Transfer (jpg/png/pdf)'),
        ),
    ]
