# Generated by Django 5.0.14 on 2025-11-11 04:07

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_created_at_donationproof_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationproof',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='donationproof',
            name='donation_type',
            field=models.CharField(choices=[('ZKT', 'Zakat'), ('INF', 'Infak'), ('SDK', 'Sedekah')], default='INF', max_length=3, verbose_name='Jenis Donasi'),
        ),
        migrations.AlterField(
            model_name='donationproof',
            name='proof',
            field=models.FileField(upload_to=core.models._proof_upload_path, verbose_name='Bukti Transfer (jpg/png/pdf)'),
        ),
        migrations.AddIndex(
            model_name='donationproof',
            index=models.Index(fields=['donation_type'], name='core_donati_donatio_5659b1_idx'),
        ),
        migrations.AddIndex(
            model_name='donationproof',
            index=models.Index(fields=['uploaded_at'], name='core_donati_uploade_cf7941_idx'),
        ),
    ]
