# Generated by Django 6.0.5 on 2026-05-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_donationproof_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('AKTA', 'Akta/Surat Wakaf'), ('SK', 'SK Pengurus/Organisasi'), ('NPWP', 'NPWP'), ('REK', 'Buku Rek Bank'), ('SOP', 'Standar Operasional Prosedur'), ('LAIN', 'Dokumen Lain')], max_length=10),
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('flow_type', models.CharField(choices=[('IN', 'Pemasukan'), ('OUT', 'Pengeluaran')], default='IN', max_length=10, verbose_name='Tipe')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Nominal (Rp)')),
                ('description', models.CharField(max_length=255, verbose_name='Keterangan')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='core.mosque')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
