# Generated by Django 6.0.5 on 2026-05-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_document_doc_type_cashflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('activity_type', models.CharField(choices=[('OPERASI', 'Aktivitas Operasi'), ('INVESTASI', 'Aktivitas Investasi'), ('PENDANAAN', 'Aktivitas Pendanaan')], default='OPERASI', max_length=15, verbose_name='Jenis Aktivitas')),
                ('flow_type', models.CharField(choices=[('IN', 'Pemasukan'), ('OUT', 'Pengeluaran')], default='IN', max_length=5, verbose_name='Tipe Arus')),
            ],
        ),
        migrations.AddField(
            model_name='cashflow',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashcategory', verbose_name='Kategori Kas'),
        ),
    ]
