# Generated by Django 6.0.5 on 2026-06-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cashcategory_cashflow_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcategory',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kode Akun'),
        ),
    ]
